### ISSUE TITLE
MhcPatcherPatches.zip missing 

### ISSUE THREAD

**Issue by trojanobelix** [VirtualFab/VGDDOpen#2]
My dream comes true. Thanks a lot, Fabio 

I can not find the MhcPatcherPatches.zip.

Best regards, DW

**Comment by parya1109** [comment]
Go to Solution Explorer>MHCPatcher>Resources and Delete the virtual path of MhcPatcherPatches.zip.

I have forked this git and pushed all fixes to https://github.com/parya1109/VGDDOpen
